# coding: utf-8

"""
    Engines API

    Allow clients to fetch Engines Analytics through APIs.  # noqa: E501

    The version of the OpenAPI document: 2
    Contact: analytics.api.support@factset.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from fds.analyticsapi.engines.configuration import Configuration


class PACalculationColumn(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'statistics': 'list[str]'
    }

    attribute_map = {
        'id': 'id',
        'statistics': 'statistics'
    }

    def __init__(self, id=None, statistics=None, local_vars_configuration=None):  # noqa: E501
        """PACalculationColumn - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._statistics = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if statistics is not None:
            self.statistics = statistics

    @property
    def id(self):
        """Gets the id of this PACalculationColumn.  # noqa: E501

        FactSet-defined or User-defined Column identifier.  # noqa: E501

        :return: The id of this PACalculationColumn.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PACalculationColumn.

        FactSet-defined or User-defined Column identifier.  # noqa: E501

        :param id: The id of this PACalculationColumn.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def statistics(self):
        """Gets the statistics of this PACalculationColumn.  # noqa: E501

        Column Statistic identifier  # noqa: E501

        :return: The statistics of this PACalculationColumn.  # noqa: E501
        :rtype: list[str]
        """
        return self._statistics

    @statistics.setter
    def statistics(self, statistics):
        """Sets the statistics of this PACalculationColumn.

        Column Statistic identifier  # noqa: E501

        :param statistics: The statistics of this PACalculationColumn.  # noqa: E501
        :type: list[str]
        """

        self._statistics = statistics

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PACalculationColumn):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PACalculationColumn):
            return True

        return self.to_dict() != other.to_dict()
